main: `#undef fallthrough` before include GUI header
Khaerul reports build error:
```
   CC     src/teavpn2/main.o
In file included from /usr/lib64/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/kh/Projects/teavpn2/src/teavpn2/gui/gui.h:14,
                 from src/teavpn2/main.c:10:
/usr/include/glib-2.0/glib/gmacros.h:632:28: error: missing ')' after "__has_attribute"
  632 | #if g_macro__has_attribute(fallthrough)
      |                            ^~~~~~~~~~~
In file included from /home/kh/Projects/teavpn2/src/teavpn2/print.h:15,
                 from /home/kh/Projects/teavpn2/src/teavpn2/common.h:19,
                 from src/teavpn2/main.c:7:
/home/kh/Projects/teavpn2/src/teavpn2/compiler_attributes.h:238:55: error: missing binary operator before token "("
  238 | # define fallthrough                    __attribute__((__fallthrough__))
      |                                                       ^
/usr/include/glib-2.0/glib/gmacros.h:632:28: note: in expansion of macro ‘fallthrough’
  632 | #if g_macro__has_attribute(fallthrough)
      |                            ^~~~~~~~~~~
make: *** [/home/kh/Projects/teavpn2/src/teavpn2/Makefile:30: /home/kh/Projects/teavpn2/src/teavpn2/main.o] Error 1
```

The `fallthrough` macro compiler_attributes.h conflicts with the macro in
gmacros. Fix this by `#undef`-ing the macro before including GUI header.

Link: https://t.me/TeaInside/47053
Reported-and-tested-by: Khaerul Ilham <khaerulilham163@gmail.com>
Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gmail.com>
Signed-off-by: Khaerul Ilham <khaerulilham163@gmail.com>
Link: https://t.me/TeaInside/47149
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>