.github/workflows: Fix missing 32-bit build library
Build bot error:
```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgtk-3-common:i386
E: Unable to locate package libgtk-3-dev:i386
Error: Process completed with exit code 100.
```

Fix this by adding 32-bit repo with:
  `sudo dpkg --add-architecture i386`

Suggested-by: Ammar Faizi <ammarfaizi2@gmail.com>
Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gmail.com>
Fixes: 30abce1d4fcba4c4337e71e3bf7accc16cb7c962 (".github/workflows: Add GUI build for GitHub build bot")
[ammarfaizi2: add Fixes tag]
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>