server/linux/udp_epoll: Fix `-Werror=unused-result`
This commit fixes this:
```
 src/teavpn2/server/linux/udp_epoll.c: In function ‘run_zombie_reaper_thread’:
src/teavpn2/server/linux/udp_epoll.c:979:2: error: ignoring return value of ‘nice’, declared with attribute warn_unused_result [-Werror=unused-result]
  979 |  nice(40);
      |  ^~~~~~~~
```

Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>